# Generated by Django 2.2.6 on 2022-10-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20221010_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Обозначение сообщества'),
        ),
    ]
